### ISSUE TITLE
python3 interactive.py error

### ISSUE THREAD

**Issue by shaunstoltz** [Skytliang/Multi-Agents-Debate#1]
Traceback (most recent call last):
  File "/home/shaunst/repo/Multi-Agents-Debate/interactive.py", line 5, in <module>
    from code.utils.agent import Agent
ModuleNotFoundError: No module named 'code.utils'; 'code' is not a package

**Comment by Skytliang** [comment]
Thanks for your issue. A minor 'ModuleNotFoundError' bug has been fixed. Try it again. :D

**Comment by shaunstoltz** [comment]
Yes, fixed... thanks!
