### ISSUE TITLE
Request for an Open Source License

### ISSUE THREAD

**Issue by David-Sat** [Skytliang/Multi-Agents-Debate#2]
I find your research very interesting and I'd like to try it out further. However, I noticed there's no license attached to it.

Would you consider adding an open source license to your repository to clarify usage permissions? GitHub provides a helpful guide [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository).

Thanks for your time and consideration.

**Comment by Skytliang** [comment]
Thank you so much for your interest in our MAD project.

We have now added a GPL-3.0 license to our repository, ensuring that users better understand how to utilize the code.

Once again, thank you for your valuable feedback and patience.

**Comment by David-Sat** [comment]
Great, thank you!
