### ISSUE TITLE
Commonsense Machine Translation Case

### ISSUE THREAD

**Issue by Hongbin-Ze** [Skytliang/Multi-Agents-Debate#3]
Could you provide more cases of Commonsense Machine Translation? That would be interesting!

**Comment by Skytliang** [comment]
Thank you so much for your interest in our MAD project.

We have now added MAD cases on CommonMT (Lexical Ambiguity) [here](https://github.com/Skytliang/Multi-Agents-Debate/tree/main/data/CommonMT/Lexical_Ambiguity/MAD_Debate_Process). Check it for more insight.

**Comment by Hongbin-Ze** [comment]
Thank you so much! Your work is very interesting!
I have another question, how much did this job call api cost approximately?

**Comment by Skytliang** [comment]
We haven't calculated the expenditure amount for the entire project yet, but it's worth mentioning that if you're using the **gpt-3.5-turbo** model, the cost of API requests is very cheap. Approximately speaking, I would say that the price expenditure is in the low thousands range (CNY).

For more details, check OpenAI API Pricing [here](https://openai.com/pricing).

**Comment by Hongbin-Ze** [comment]
Many thanks!
