### ISSUE TITLE
How many questions do you have on that mathematical reasoning data? 

### ISSUE THREAD

**Issue by zwq2018** [Skytliang/Multi-Agents-Debate#4]
How many questions do you have on that mathematical reasoning data? The paper claims there are only 50 questions? Only 10 questions in the code file?

**Comment by Skytliang** [comment]
We release Counter-Intuitive AR dataset [here](https://github.com/Skytliang/Multi-Agents-Debate/blob/main/data/CounterintuitiveQA/CIAR.json), which contains 50 questions.

**Comment by zwq2018** [comment]
50 questions are not enough for a comprehensive evalution

**Comment by Skytliang** [comment]
We acknowledge this issue, and we will consider expanding the dataset as much as possible, at least to 100 questions. Thank you for your feedback and suggestions.
