### ISSUE TITLE
How to use Open Source LLM for LLM Multi Agent Debate?

### ISSUE THREAD

**Issue by 2018211801** [Skytliang/Multi-Agents-Debate#5]
hello~thanks for your interesting job! Should I use LLAMA through an API in your program?

**Comment by Skytliang** [comment]
Hi there,

You can deploy your own LLMs like LLama 2, Vicuna, and Alpaca using [FastChat](https://github.com/lm-sys/FastChat). It supports OpenAI-compatible APIs and provides instructions [here](https://github.com/lm-sys/FastChat/blob/main/docs/openai_api.md#openai-compatible-restful-apis).
